### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by edwardando** [christian-7/MultiColorSPR#18]
Dear developers,
We're interested in uploading this software onto the "Imaging plaza" to increase its visibility as an EPFL-related imaging software, but we don't understand the license.
Judging by a commit message this is BSD, do you confirm?

EDIT: there IS a license but github API doesn't pick it up...

**Comment by kmdouglass** [comment]
@edwardando I think this is fixed now. Let me know if you need anything else.

**Comment by edwardando** [comment]
Thanks, sorry for the messy issue

**Comment by kmdouglass** [comment]
Sorry @edwardando I missed your edits on the issue.

The BSD3 license is now explicit and recognized by GitHub's API.
